### ISSUE TITLE
automatic refresh when window resizes

### ISSUE THREAD

**Issue by pbellec** [brainsprite/brainsprite#16]

**Comment by kchapelier** [comment]
I'll probably provide a PR to this effect this weekend. I already have a mostly working naive solution, but it could probably be optimized to avoid some of the unecessary extra work it is currently doing. Will see.

**Comment by pbellec** [comment]
This would be great, that's been on my list of things to do for two years :) 
Thanks a lot for looking into that.

**Comment by pbellec** [comment]
big thanks @kchapelier
