### ISSUE TITLE
document how to include a brainsprite as an iframe using nilearn

### ISSUE THREAD

**Issue by pbellec** [brainsprite/brainsprite#63]

**Comment by gkiar** [comment]
To generate a sprite in Python for a T1w image I did the following:

```python
from nilearn.plotting import view_img
import nibabel as nib

img = nib.load("my_image.nii.gz")
html_view = plotting.view_img(img, bg_img=None, colorbar=False,
                              annnotate=False, cmap="gray", 
                              symmetric_cmap=False, black_bg=True)
html_view.save_as_html("my_sprite.html")
```

Then for including it in a page, I just did the following

```html
<iframe src="my_sprite.html" height=250 style="padding:0; border:0"></iframe>
```

Note: this doesn't include anything like adjusting the vmin and vmax to improve contrast, etc...

**Comment by emdupre** [comment]
One thing I'd love documentation for, if possible, is how to add a contour to a nilearn-generated brainsprite. I know from #25 that these contours need to be generated in 3D -- still unclear to me how that can be incorporated when calling from nilearn !

**Comment by pbellec** [comment]
This issue is too old. Closing.

**Comment by pbellec** [comment]
mmmhh the snippet actually badly needs to land in the docs. Re-opening with appropriate label.
