### ISSUE TITLE
use tempita for templating in nilearn's `view_img

### ISSUE THREAD

**Issue by pbellec** [brainsprite/brainsprite#70]
While doing so, the snippet and template generation can be made more granular, so that it will accomodate more complex use cases, such as dashboard generation.

**Comment by pbellec** [comment]
check example snippet here
https://github.com/nilearn/nilearn/blob/ab4db4a0a130061791947434df16b97b607b843d/nilearn/reporting/html_report.py#L57

**Comment by emdupre** [comment]
Very excited for this ! Please ping if I can help 👍
