### ISSUE TITLE
consistency issue with the opacity parameter for the overlay

### ISSUE THREAD

**Issue by kchapelier** [brainsprite/brainsprite#77]
The parameter is placed in the `overlay` object in /tests/demo.html, /tests/example_colormap.html, /tests/example_overlay.html and /tests/example_value.html. But it is placed directly at the root of the `params` object in /tests/example_full.html.

Currently the codebase only supports it when it is at the root of the `params` object. From my point of view it would have more sense for it to be in the `overlay` object (or to be renamed overlayOpacity).

**Comment by pbellec** [comment]
Agreed with the suggestion. Do not hesitate if you have others, I was planning on refreshing the API anyways. I will create an API branch, and merge all API changes in a single release, to avoid breaking the API repeatedly.
