### ISSUE TITLE
performance audit/optimization

### ISSUE THREAD

**Issue by kchapelier** [brainsprite/brainsprite#78]
I understand this may not come at the best of times as you're currently switching from a test framework to another but let me know if you'd be interested in some kind of external performance audit/optimization of the javascript library.

**Comment by pbellec** [comment]
This would be extremely useful indeed. I have developed brainsprite in part as a side project to learn javascript. And I still suck at it. I am sure the code base could be dramatically improved and modularized. But as you pointed out, I do need to set up the tests before this can be moved forward. This is quite a bit of work as I am integrating the tests with documentation generation. Will tag you here when it's done.

**Comment by pbellec** [comment]
@kchapelier the test suite is now functional. If you open a pull request, the tests will run automatically on circleci. If that's how you'd like to proceed, no need to read what's below. 

If you want to run tests locally, I still need to add a "dev" section in the new documentation, but here is the short version: 
 * install brainpsrite.py from the brainsprite folder
 * install js dev dependencies with `npm` using `package.json`
 * install py dev dependencies form `docs/requirements.txt`
 * run `npm test`

You can check the detailed circle test workflow in `.circleci/config.yml`. FYI running the dev convenience script `./update` will run all tests and build the new documentation site inside `docs/build`  

If a test fails, look at the `*_diff.png` images in the `tests` folder, they will tell you what has changed in the appearance of the viewer compared to a reference, approved version.

If you believe the changes make sense, based on the features you are adding (although I don't think this audit will bring user-visible change), you can change the reference images using:
```
./update -t 
``` 

Thanks in advance for your help.

**Comment by kchapelier** [comment]
@pbellec 👍  I'll start to look at it in details this friday.

**Comment by kchapelier** [comment]
Some first results.

Most of the CPU time is spent processing the calls to the canvas context (drawImage and getImageData specifically), instead of dealing with pure javascript calculations. This is true both when instantiating brainsprite and when clicking on the canvas to update the value / change the coordinates.

When clickBrain is called on an instance with an overlay and a colorMap about half of the time is spent redrawing the scene, the other half is spent updating the value. This may vary depending on the source images and the colorMap size, but in my case this is true when clicking on the sagital plane, both operations were taking about 1.2ms.

This [change](https://github.com/kchapelier/brainsprite/commit/31284d04484cd5f688450332640a5447f428e27b) reduces the time to update the value from 1.3/1.1ms to 0.2/0.1ms. The idea is to call getImageData only once since the method is rather costly and to manually iterate over each pixel in the array.

I haven't benchmarked the following changes (and I don't expect them to have much impact since they do not reduce the number of calls to the canvas context) but for the [first one](https://github.com/kchapelier/brainsprite/commit/7c2dda3ae9fa6f26130cf823e6c97297ba938a43) the multiply function was swapped in favor of a specific (more simple) vec4 * matrix4 function. The change also avoid multiple array instantiations and make sure coordinatesSlice receives the data as scalars. Previously coordinatesSlice was receiving arrays with a single element, but Javascript's automatic type conversion was transparently ironing out the issue.

The [last change](https://github.com/kchapelier/brainsprite/commit/61065fd0fdda576e79f2c028a26385f3cda6d7b5) simplifies how the overlay color is checked for transparency in the updateValue function. Instead of drawing the color two times on solid black and white, the canvas is set to transparent so that the alpha value can be directly retrieved and tested.

I'll do a proper PR with those changes this week-end. There is also another optimization I want to investigate but it would imply a lot of changes and while it should improve the runtime performances (drawAll), it might cause some overhead at the initialization...

**Comment by kchapelier** [comment]
@pbellec I was wondering if you made some tests with high resolution images and if this is the case, where was the perceived bottleneck in terms of performance, is it during the initialisation or is it having trouble to update the planes when the coordinates are changed ?

**Comment by pbellec** [comment]
This is awesome! Very interesting that the basic maths operations ended up costing as much as the actual drawing, huge thanks for sorting that out. Very much looking forward to the PR. 

In terms of bottleneck, I never tried loading very large brain images, but I did try (and successfully implement) a dashboard with 80 synced viewers. The bottleneck was the drawing of the coronal and axial views. What I ended up doing was pre-build all slices in the three planes. It took a while to load, but once loaded it was much faster to draw, and I was able to move through the 80 brains at once relatively smoothly. But it also means that each sprite was duplicated three times in memory. I ended up scrapping that code (I think) because it was too much of a niche use case.

I could try to get some high res brain data to check if it is smooth.

**Comment by kchapelier** [comment]
The other optimization I wanted to investigate has more overhead than I hoped. The idea was to avoid drawImage and getImageData calls as much as possible at runtime, by loading the sprite, overlay and colorMap as imageData at the initialization and to manually populate the pixel values of a single ImageData containing all the slices/planes in drawAll(). The issue is that getting the full imageData of a sprite of 2000px/2000px at the initialization takes about 100ms. Doing it for both the sprites and the overlay at a larger resolution might get close to half a second. It doesn't seem like such a good idea anymore.

**Comment by pbellec** [comment]
it would also come with a big memory overhead. I agree this may not be worth it. 

FYI I want to add support for different voxelSize in the background and overlay brain images. Images would still need to have same spatial orientation and field of view, but one could have bigger voxels. As overlays are often much lower resolution, there may be big gains working like that, at least in terms of memory footprint.

**Comment by kchapelier** [comment]
I'm curious, did you ever run in a situation where memory became an issue (with multiple views or in a "nilearn" integration ?), or is it more of a preemptive action ?

**Comment by pbellec** [comment]
It is more preemptive at this stage. However, I am planning to implement a 4D viewer extension soon, and upsampling the fMRI overlay to high (T1) resolution would actually be a memory hog.

**Comment by pbellec** [comment]
it looks like we are done with the optimization at least for now, with the merge of https://github.com/brainsprite/brainsprite/pull/94 I am closing the issue.
